apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # Or your default Minikube storage class
  resources:
    requests:
      storage: 5Gi # Adjust as needed
