apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: immich
type: Opaque
data:
  DB_PASSWORD: <Your Password here>  # Must match postgres-secret
  JWT_SECRET: <Your Secret here> 
  # Add other secrets like TYPESENSE_API_KEY if needed
