apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: immich
type: Opaque
data:
  DB_PASSWORD: VHNlZW5hb3BzITMzNw==  # Must match postgres-secret
  JWT_SECRET: NDBkNjcxOGYwOTEyZDFkYmIyMmIxMDc0NTllN2QzZjA2NTgxNmYzYjEwODQ0MTVlOTgyMzFhZWRjMmNkYWE4ZQ==
  # Add other secrets like TYPESENSE_API_KEY if needed
