apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - redis-deployment.yaml
  - immich-configmap.yaml
  - immich-secret.yaml
  - immich-pvc.yaml
  - immich-server-deployment.yaml
  - immich-microservices-deployment.yaml
  - immich-web-deployment.yaml
  - immich-machine-learning-deployment.yaml # Optional
  - immich-ingress.yaml
