name: Kubernetes Manifest CI

on:
  push:
    branches:
      - main # Or your primary branch
  pull_request:
    branches:
      - main

jobs:
  lint-k8s-manifests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Kubeval
      uses: instrumental/kubeval-action@v1 # Or use Kustomize build + kubeconform
      with:
        files: . # Directory containing your manifests

    # Example using Kustomize build and kubeconform (more robust)
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Setup kubeconform
      uses: yokawasa/action-setup-kube-tools@v0.9.0
      with:
        kubeconform: '0.6.3' # Specify version

    - name: Validate PostgreSQL manifests with Kustomize and Kubeconform
      run: |
        kustomize build postgresql/ | kubeconform -strict -summary

    - name: Validate Immich manifests with Kustomize and Kubeconform
      run: |
        kustomize build immich/ | kubeconform -strict -summary
